### ISSUE TITLE
This project is similar with flask-restaction, interested to have a look?

### ISSUE THREAD

**Issue by guyskk** [winkidney/schema-sugar#9]
I found this project from http://www.v2ex.com/t/302731 ，it it very similar with https://github.com/guyskk/flask-restaction, most feature already implemented. 

Welcoming feedback :)

**Comment by winkidney** [comment]
@guyskk Hi，之前也在邮件组看到过falsk-restaction，非常赞的概念~
其实在实现SchemaSugar初期就看到了flask-restaction，可能在解决的问题上有些不同。
flask-restaction做了js自动生成，文档生成（这个似乎还没看到实现：），validater很赞啊，不过可能会有少许学习成本？
SchemaSugar使用的是类似Rails的Resource definition，而且想要自动生成命令行，不知道flask-restaction有没有这方面的roadmap~

**Comment by guyskk** [comment]
@winkidney 
validater 刚开始用会觉得有点难，毕竟那个schema是新东西。schema可以直接当做API文档，可读性没有问题(这点我和前端讨论过，他们觉得可以，现在也是这样用)。文档生成目前是直接显示json格式的schema，搭配浏览器的json格式化插件使用，目前问题主要是很长的desc放到json里面不好看，API很多的话跳转不是特别方便。最近也在计划生成html格式的文档，增加文档的易用性，打算在文档里集成一个交互式的操作API的界面，参考 https://rethinkdb.com/ 。

关于自动生成命令行，flask-restaction只有两层，resource和action，所以最多只能实现 `docker images` 这样两个层级的命令，实现的话可以利用这个 http://flask-restaction.readthedocs.io/zh/stable/api.html#res 。

**Comment by winkidney** [comment]
@guyskk 我之前是参考的http://guides.rubyonrails.org/routing.html，所有资源的操作都抽象成CRUD+extra action，所以资源方面其实定义的支持更加宽泛一些
使用flask的blue print，可以简单的实现复杂路径资源的生成：）
Schema方面使用的JsonSchema（一个现成的标准）

交互式API操作点赞！

**Comment by guyskk** [comment]
@winkidney 当初我也考虑过资源定义的问题，最后还是选择不用 `/photos/17` 这样的URL表示资源，我将资源定义为一类资源，而不是某个具体的资源，因为定义为一类资源处理起来方便，URL中不含参数。

不用JSONSchema是因为这个学习成本也挺高，可读性不够好，校验数据也不方便。当然支持标准也有好处，比如可以用 swagger.io 这样现成的工具。

**Comment by guyskk** [comment]
@winkidney Hi
flask-restaction 的 html 格式的API文档完成了
http://flask-restaction.readthedocs.io/zh/stable/quickstart.html#api
可以通过chrome控制台直接操作API，所以没有集成交互式界面。

**Comment by guyskk** [comment]
有什么问题的话，可以到这里提issue:
https://github.com/guyskk/flask-restaction/issues
感谢尝试&体验flask-restaction框架！

**Comment by winkidney** [comment]
@guyskk 赞啊，看到了文档生成：）清晰易懂
